openapi: 3.0.0
info:
  title: API Orders
  description: Simple API to manege Orders
  version: 1.0.0
servers:
  - url: /api/orders
    description: localhost for test and development
paths:
  /orders:
    get:
      summary: List all orders
      description: Returns a list of orders registred in the db
      responses:
        '200':
          description: List of Orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
    post:
      summary: Create a new Order
      description: Register a new order in the db
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '201':
          description: Order created correctly
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '422':
          description: Validation Erro
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  errors:
                    type: object

  /orders/{id}:
    get:
      summary: Show a specific order
      description: Return the order details based on the id.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the order
      responses:
        '200':
          description: Details of the order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: Order not found
    put:
      summary: Update an order
      description: Updates the information of an existing Order
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID from the order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: Order updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: Ordered not found
        '422':
          description: Validation error
    delete:
      summary: Delete an existing Order
      description: Delete an order.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID from the order
      responses:
        '204':
          description: Order deleted successfully
        '404':
          description: Order not found

components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          example: 1
        customer_name:
          type: string
          example: "Adrià Jordà"
        product:
          type: string
          example: "Laravel Book"
        quantity:
          type: integer
          example: 2
        total_price:
          type: number
          format: float
          example: 49.99
        order_date:
          type: string
          format: date
          example: "2026-01-05"
        status:
          type: string
          example: "pending"
        created_at:
          type: string
          format: date-time
          example: "2026-01-05T12:00:00Z"
        updated_at:
          type: string
          format: date-time
          example: "2026-01-05T12:00:00Z"
      required:
        - customer_name
        - product
        - quantity
        - total_price
        - order_date
